In [31]:
import numpy as np
import pandas as pd

In [32]:
arr = np.random.normal(10, 10, (3, 2))

In [40]:
id(arr)

140597975026624

In [50]:
id(df.values)

140597949128576

In [33]:
arr[0, 1] = 3

In [76]:
arr.flags.owndata, df.values.flags.owndata

(True, False)

In [78]:
df.iloc[:, :].values.flags.owndata

False

In [51]:
arr[0, 0] = 3

In [69]:
df.values[0, 0] = -100

In [70]:
df

a          b
0 -100.000000   3.000000
1   10.266603   3.030181
2    8.853013  13.000104

In [46]:
df = pd.DataFrame(arr, columns = ['a', 'b'])

In [66]:
id(df.iloc[:, :]), id(df)

(140597966537104, 140597966537104)

In [68]:
id(df) is id(df.iloc[:, :]), id(df) == id(df.iloc[:, :])

(False, True)

In [37]:
def test(df):
    print(id(df))
    df.iloc[0, 0] = 1
    return df

In [38]:
test(df)

140597973789840


a          b
0   1.000000   3.000000
1  10.266603   3.030181
2   8.853013  13.000104

In [23]:
df

a          b          c
0   0.000000  13.345815  17.003526
1  10.984075  24.152888  25.181038
2  20.356930   2.092596  11.256909
3  -7.788763  17.251363  18.079046
4  14.081156   4.402983  12.778452
5   8.378902  27.234727  21.537407
6  20.689117  -1.519983  22.868932
7   3.013332  13.539505   1.400438
8  -2.870640   2.132458  12.486637
9   7.748373  -6.953009   1.343720

In [24]:
arr

array([[ 0.        , 13.34581504, 17.0035259 ],
       [10.98407499, 24.15288827, 25.18103774],
       [20.35692965,  2.09259606, 11.25690885],
       [-7.78876304, 17.25136329, 18.0790455 ],
       [14.08115603,  4.40298275, 12.77845183],
       [ 8.37890186, 27.23472694, 21.53740712],
       [20.6891167 , -1.51998262, 22.86893158],
       [ 3.01333184, 13.53950462,  1.40043752],
       [-2.8706399 ,  2.13245829, 12.48663662],
       [ 7.7483729 , -6.95300902,  1.34371956]])

In [26]:
a

12.659926287538113

In [27]:
b

array([[22.65992629]])

In [32]:
arr

array([[10.78276309, 22.65992629,  7.80626587],
       [19.53123286, 31.48644925,  9.36254057],
       [22.54812468, 22.80244023, 17.79821949],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694],
       [24.4401901 , 36.78733261, 18.26561618],
       [17.64695695,  6.24631652,  1.4409482 ],
       [18.55793308, 19.94417017, -0.16571184],
       [-2.43223166, 42.27359383, 31.02579337],
       [ 2.08955311, 12.29812559,  7.82407124]])

In [28]:
mask = np.array([0, 3, 4])

In [31]:
masked = arr[mask]

In [35]:
masked[0:1, 0:1] = -1

In [36]:
masked

array([[-1.        , 22.65992629,  7.80626587],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694]])

In [37]:
arr

array([[10.78276309, 22.65992629,  7.80626587],
       [19.53123286, 31.48644925,  9.36254057],
       [22.54812468, 22.80244023, 17.79821949],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694],
       [24.4401901 , 36.78733261, 18.26561618],
       [17.64695695,  6.24631652,  1.4409482 ],
       [18.55793308, 19.94417017, -0.16571184],
       [-2.43223166, 42.27359383, 31.02579337],
       [ 2.08955311, 12.29812559,  7.82407124]])

In [40]:
mask = [True, True] + [False] * 8

In [42]:
masked = arr[mask]

In [43]:
arr

array([[10.78276309, 22.65992629,  7.80626587],
       [19.53123286, 31.48644925,  9.36254057],
       [22.54812468, 22.80244023, 17.79821949],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694],
       [24.4401901 , 36.78733261, 18.26561618],
       [17.64695695,  6.24631652,  1.4409482 ],
       [18.55793308, 19.94417017, -0.16571184],
       [-2.43223166, 42.27359383, 31.02579337],
       [ 2.08955311, 12.29812559,  7.82407124]])

In [45]:
masked[:, 1] = -1

In [46]:
masked

array([[10.78276309, -1.        ,  7.80626587],
       [19.53123286, -1.        ,  9.36254057]])

In [47]:
arr

array([[10.78276309, 22.65992629,  7.80626587],
       [19.53123286, 31.48644925,  9.36254057],
       [22.54812468, 22.80244023, 17.79821949],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694],
       [24.4401901 , 36.78733261, 18.26561618],
       [17.64695695,  6.24631652,  1.4409482 ],
       [18.55793308, 19.94417017, -0.16571184],
       [-2.43223166, 42.27359383, 31.02579337],
       [ 2.08955311, 12.29812559,  7.82407124]])

In [48]:
arr

array([[10.78276309, 22.65992629,  7.80626587],
       [19.53123286, 31.48644925,  9.36254057],
       [22.54812468, 22.80244023, 17.79821949],
       [ 4.66668338, 47.78010345,  6.88981175],
       [ 9.13291101, 21.97648248, 27.23611694],
       [24.4401901 , 36.78733261, 18.26561618],
       [17.64695695,  6.24631652,  1.4409482 ],
       [18.55793308, 19.94417017, -0.16571184],
       [-2.43223166, 42.27359383, 31.02579337],
       [ 2.08955311, 12.29812559,  7.82407124]])

In [49]:
b = arr

In [50]:
id(b)

140106190568864

In [51]:
id(arr)

140106190568864